---
title: "Exer2_graficos"
date: "11/30/2019"
output: html_document
---
```{r}

library(dplyr)
library(tidyr)
library(ggplot2)

```


Lendo o arquivo e gerando um dataset com as princiapais variaveis.

```{r}
df <- read.csv2('datasets/CEAPS.csv', encoding="Latin-ASCII",stringsAsFactors = FALSE)
df <- iconv(df, "latin1", "UTF-8")
df$VALOR_REEMBOLSADO <-as.numeric(gsub(",", ".", as.character(df$VALOR_REEMBOLSADO)))


df_gastos <- df %>%
  select(ANO, MES, SENADOR, VALOR_REEMBOLSADO)



sum(is.na(df))
```



```{r}
df
```



```{r}
g_2018 <- filter(df_gastos, ANO == 2018)
g_2018 <- group_by(g_2018, SENADOR) %>%
  summarise(Total = sum(VALOR_REEMBOLSADO))
g_2018
```

Os 10 Senadores que mais tevera
```{r}
g_2018_ord <- g_2018[order(-g_2018$Total),]
ggplot(data = g_2018_ord[1:10,], aes(x = reorder(SENADOR, Total), y = Total)) +  
  geom_bar(stat = "identity") +
  coord_flip() 

```

Outra maneira de fazer os top 10.

```{r}
g_2018 %>%
  top_n(10, Total) %>%
  ggplot(aes(x=reorder(SENADOR, Total), y = Total),) + 
  geom_col(aes(fill = Total)) +
  xlab("Senadores") + ylab("Valores Reembolsados em 2018") +
  coord_flip()

```

Senador que mais teve reembolso.

```{r}
top_reemb <- group_by(df_gastos, SENADOR) %>%
  summarise(Total = sum(VALOR_REEMBOLSADO)) %>%
  arrange(desc(Total))
top_reemb
```

Gráfico em linha com evolução do Senador com maior valor total reembolsado.

```{r}
senador <- df_gastos %>%
  filter(SENADOR == top_reemb$SENADOR[1]) %>%
  group_by(ANO) %>%
  summarise(Total = sum(VALOR_REEMBOLSADO))

senador %>%
  ggplot() + 
  geom_line(aes(x=ANO, y=Total/1000), size=1) +
  xlim(2007,2020) + ylab("Valores em K") 

```

Comparação entre os 3 Senadores que mais receberam reebolso.


```{r}
top_1 <- top_reemb[1,]
top_2 <- top_reemb[2,]
top_3 <- top_reemb[3,]

plot_1 <- df_gastos %>%
  filter(SENADOR == top_1$SENADOR) %>%
  group_by(SENADOR, ANO ) %>%
  summarise(Total = sum(VALOR_REEMBOLSADO))
plot_2 <- df_gastos %>%
  filter(SENADOR == top_2$SENADOR) %>%
  group_by(SENADOR, ANO ) %>%
  summarise(Total = sum(VALOR_REEMBOLSADO))
plot_3 <- df_gastos %>%
  filter(SENADOR == top_3$SENADOR) %>%
  group_by(SENADOR, ANO ) %>%
  summarise(Total = sum(VALOR_REEMBOLSADO))

a <- ggplot(data = plot_1) + geom_line(aes(x=ANO, y=Total/1000), size=1, color="blue")  
b <- ggplot(data = plot_2) + geom_line(aes(x=ANO, y=Total/1000), size=1, color="red")
c <- ggplot(data = plot_3) + geom_line(aes(x=ANO, y=Total/1000), size=1, color="green")

grid.arrange(a,b,c, ncol=1)
```



```{r}
top_reemb %>%
  top_n(1000, Total) %>%
  ggplot(aes(x=Total)) + 
  geom_histogram(fill="skyblue", bins = 20)

```

```{r}
top_reemb
```
```{r}
top_reemb %>%
  ggplot() +
  geom_point(mapping = aes(x=SENADOR, y=Total))
  
```

```{r}
top_reemb %>%
  top_n(10, Total) %>%
  ggplot() +
  geom_bar(mapping = aes(x=SENADOR, fill = SENADOR), show.legend = FALSE, width = 1) +
  theme(aspect.ratio = 1) +
  labs(x=NULL, y=NULL) +
  coord_polar()
  
```



```{r}

top_reemb %>%
  top_n(5, Total) %>%
treemap(data,index = c("SENADOR"),vSize ="Total")

```

